Algoritmo "Calcula_soma_media"
// Criação de aplicações e sistemas
// Franklin Portela 
// Descrição: Calcula soma e a média de 3 números
// Autor: Marcus Vieira
// Data atual: 10/04/2022
Var
num1: real
num2: real
num3: real
soma: real
media: real

Inicio
num1 <- 2
num2 <- 4
num3 <- 8

soma <- num1 + num2 + num3
media <- soma / 3

Escreval("A soma entre", num1, num2, num3, " é:", soma)
Escreval("A média entre", num1, num2, num3, " é:", media)

Fimalgoritmo