Algoritmo "20220415_Exemplo_IO"
// Criação de aplicações e sistemas
// Franklin Portela 
// Descrição: Aqui você descreve o que o programa faz! (função)
// Autor: Marcus Vieira
// Data atual: 15/04/2022
Var
num1: Real
num2: Real
resultado: Real

Inicio
Escreval("Digite um número: ")
Leia(num1)
Escreval("Digite outro número")
Leia(num2)

resultado <- num1 / num2

Escreval("Os números são", num1, " e", num2)
Escreval("O resultado da expressão matemática é", resultado)

Fimalgoritmo